name: mp_venv
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel>=6.30
  - matplotlib>=3.9
  - nbformat>=4.2.0
  - numpy>=2.0
  - python>=3.9
  - pandas>=2.3
  - plotly>=6.3
  - scikit-learn>=1.6
  - scipy>=1.13